spring:
  datasource:
    url: jdbc:h2:mem:claro2024
    username: claro2024
    password: 
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create  # cria e remove o banco a cada execução de teste
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
